CREATE TABLE public.email_summaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_id bigint REFERENCES public.emails(id) ON DELETE CASCADE,
  summary text NOT NULL,
  key_points text[],
  sentiment text CHECK (sentiment IN ('positive', 'neutral', 'negative')),
  action_required boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_email_summaries_email_id ON public.email_summaries(email_id);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_email_summaries_updated_at
BEFORE UPDATE ON public.email_summaries
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
