CREATE TABLE public.requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_id bigint REFERENCES public.emails(id) ON DELETE SET NULL,
  title text NOT NULL,
  category text NOT NULL CHECK (category IN (
    'Room Booking', 'Club Permission', 'IT Access',
    'Budget Approval', 'Event Approval', 'Other'
  )),
  description text,
  department text,
  urgency text DEFAULT 'normal' CHECK (urgency IN ('low', 'normal', 'high', 'critical')),
  requester_name text,
  requester_email text,
  risk_score numeric(5,2),
  risk_level text CHECK (risk_level IN ('low', 'medium', 'high')),
  ai_summary text,
  ai_recommendation text,
  ai_confidence numeric(5,2),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'auto_approved', 'approved', 'rejected', 'escalated'
  )),
  reviewed_by uuid REFERENCES public.profiles(id),
  reviewed_at timestamptz,
  admin_notes text,
  submitted_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_requests_status ON public.requests(status);
CREATE INDEX idx_requests_risk_level ON public.requests(risk_level);
CREATE INDEX idx_requests_category ON public.requests(category);
CREATE INDEX idx_requests_requester_email ON public.requests(requester_email);
CREATE INDEX idx_requests_submitted_at ON public.requests(submitted_at DESC);

CREATE TRIGGER set_requests_updated_at
BEFORE UPDATE ON public.requests
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
