CREATE TABLE public.activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint REFERENCES public.requests(id) ON DELETE SET NULL,
  email_id bigint REFERENCES public.emails(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN (
    'request_submitted', 'risk_scored', 'auto_approved',
    'escalated', 'approved', 'rejected', 'reviewed', 'info_requested'
  )),
  actor_id uuid REFERENCES public.profiles(id),
  actor_name text,
  notes text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX idx_activity_log_request_id ON public.activity_log(request_id);
CREATE INDEX idx_activity_log_created_at ON public.activity_log(created_at DESC);
